### ISSUE TITLE
[Array type required] 

### ISSUE THREAD

**Issue by ESP32DE** [lakeofsoft/vcp#1]
Hi Oleksandr

first, many thanks for the opensource and openview your fantastic code.

i try to compile the packages and install it, but i get a small "delphi type" mistake error
from delphi 7 enterprise with the following message:

_This error message is given if you either index into an operand that is not an array, or if you pass an argument that is not an array to an open array parameter._

the code place is [here](https://github.com/lakeofsoft/vcp/blob/b5823034e88ca65fe04c1c21892be6b3337c8f27/common/unaSocks_RTP.pas#L4693)

The delphi help says as example:

```
program Produce;
var
  P: ^Integer;
  I: Integer;
begin
  Writeln(P[I]);
end.
```

We try to apply an index to a pointer to integer - that would be legal in C, but is not in Delphi. 

```
program Solve;
type
  TIntArray = array [0..MaxInt DIV sizeof(Integer)-1] of Integer;
var
  P: ^TIntArray;
  I: Integer;
begin
  Writeln(P^[I]);   (*Actually, P[I] would also be legal*)
end.
```

In The Delphi language, we must tell the compiler that we intend P to point to an array of integers.

perhabs you can [check the line](https://github.com/lakeofsoft/vcp/blob/b5823034e88ca65fe04c1c21892be6b3337c8f27/common/unaSocks_RTP.pas#L4693) - i will try to check it too

Many thanks again for your fantastic code!

best wishes
rudi ;-)

**Comment by lakeofsoft** [comment]
hm, PByte should have no problem with indexing, even in Delphi 7 I believe. Anyways, the line should be as simple as:

`inc(pByte(hdr), 2);`

will fix now, thank you for reporting.
